apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: node-redis
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: node-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis
spec:
  selector:
    matchLabels:
      app: node-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: node-redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
         
     
